AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for docker-app
Globals:
  Function:
    Timeout: 3

Resources:
  S3LambdaOnlyS3Policy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: s3-lambda-only
      PolicyDocument:
        Statement:
          - Action:
              - 's3:*'
            Effect: 'Allow'
            Resource: !Sub 'arn:aws:s3:::${S3LambdaOnly}/*'
            Principal: '*'
  S3LambdaOnly:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-lambda-only

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt DockerRevenFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !GetAtt S3LambdaOnly.Arn

  DockerRevenFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 60
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: s3-lambda-only
        - S3WritePolicy:
            BucketName: bucket-store-blossv1
      Events:
        FileUpload:
          Type: S3
          Properties: 
            Bucket: !Ref S3LambdaOnly
            Events: s3:ObjectCreated:*
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src
      DockerTag: python3.9-v1

Outputs:
  DockerRevenFunction:
    Description: "Docker Lambda Function ARN"
    Value: !GetAtt DockerRevenFunction.Arn
  DockerRevenFunctionIamRole:
    Description: "Implicit IAM Role created for Docker function"
    Value: !GetAtt DockerRevenFunctionRole.Arn
